# Generated by Django 5.2.4 on 2025-07-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_candidate_resume_analysis_alter_candidate_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='transcript',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
