# Generated by Django 5.2.4 on 2025-07-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_complete',
            field=models.BooleanField(default=False),
        ),
    ]
